In [20]:
import torch
import numpy as np

### 建立張量

In [6]:
# 0維tensor (scalar)
t1 = torch.tensor(1, dtype=torch.int16)
print(t1.shape)
t1

torch.Size([])


tensor(1, dtype=torch.int16)

In [7]:
# 1維tensor (vector)
t2 = torch.tensor([1,2,3], dtype=torch.float32)
print(t2.shape)
t2

torch.Size([3])


tensor([1., 2., 3.])

In [9]:
# 2維tensor (matrix)
t3 = torch.tensor([[1.,2,5],[3,4,6]])
print(t3.shape)
t3

torch.Size([2, 3])


tensor([[1., 2., 5.],
        [3., 4., 6.]])

In [12]:
# 3維tensor (n-dimensional array)
t4 = torch.tensor([[[1, 2, 3], [3, 4, 5]],
                    [[5, 6, 7], [7, 8 ,9]]])
print(t4.shape)
t4

torch.Size([2, 2, 3])


tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])

In [13]:
# torch.randn: 由平均值為0，標準差為1的常態分佈中，抽樣元素組成給定形狀的張量
t5 = torch.randn((2,3,5))
print(t5.shape)
t5

torch.Size([2, 3, 5])


tensor([[[ 0.2466,  0.3399,  0.7305, -2.6814,  1.1299],
         [ 0.8867,  1.4444,  0.3206, -1.3668, -0.3943],
         [-1.1321, -0.2890,  0.8228,  0.5166, -0.3175]],

        [[ 0.5961, -0.2819,  0.7204, -1.1988,  0.2252],
         [ 0.3511, -0.8501,  0.5614, -1.3559,  0.1657],
         [-1.3626, -2.8064,  0.6248,  0.4954,  1.1117]]])

In [14]:
# torch.randint: 在給定的上下界(預設下界為0)中抽樣"整數"元素組成給定形狀的張量
t6 = torch.randint(low=0, high=10, size=(3,2))
print(t6.shape)
t6

torch.Size([3, 2])


tensor([[8, 4],
        [3, 3],
        [9, 1]])

In [15]:
# torch.ones: 產生給定形狀，元素全為1的張量
t7 = torch.ones((2,3))
print(t7.shape)
t7

torch.Size([2, 3])


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [16]:
# torch.ones_like: 產生與給定張量相同形狀，但元素全為1的張量
t8 = torch.ones_like(t6)
print(t8.shape)
t8

torch.Size([3, 2])


tensor([[1, 1],
        [1, 1],
        [1, 1]])

### 張量與陣列轉換

In [22]:
# 產生numpy ndarray
x = np.array([[1.,2],[3,4],[5,6]])
print(x.shape)
x

(3, 2)


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [23]:
# 由numpy ndarray產生pytorch tensor
y = torch.from_numpy(x)
# y = torch.tensor(x) 也可以達到同樣效果
print(y.shape)
y

torch.Size([3, 2])


tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [24]:
# 檢查array與tensor的資料型態
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [25]:
# 將tensor轉換為array
z = y.numpy()
print(z.shape)
z

(3, 2)


array([[1., 2.],
       [3., 4.],
       [5., 6.]])

### 張量運算

In [38]:
# 創建tensor
a = torch.tensor([[1,2],[4,8]], dtype=torch.float32)
b = torch.tensor([1,2], dtype=torch.float32)
print(a.shape,b.shape)
a, b

torch.Size([2, 2]) torch.Size([2])


(tensor([[1., 2.],
         [4., 8.]]),
 tensor([1., 2.]))

In [39]:
# 相加
t_add1 = a + b
t_add2 = torch.add(a,b)
print(t_add1.shape, t_add2.shape)
t_add1, t_add2

torch.Size([2, 2]) torch.Size([2, 2])


(tensor([[ 2.,  4.],
         [ 5., 10.]]),
 tensor([[ 2.,  4.],
         [ 5., 10.]]))

In [40]:
# 相減
t_sub1 = a - b
t_sub2 = torch.sub(a,b)
print(t_sub1.shape, t_sub2.shape)
t_sub1, t_sub2

torch.Size([2, 2]) torch.Size([2, 2])


(tensor([[0., 0.],
         [3., 6.]]),
 tensor([[0., 0.],
         [3., 6.]]))

In [41]:
# 相除
t_div1 = a / b
t_div2 = torch.div(a,b)
print(t_div1.shape, t_div2.shape)
t_div1, t_div2

torch.Size([2, 2]) torch.Size([2, 2])


(tensor([[1., 1.],
         [4., 4.]]),
 tensor([[1., 1.],
         [4., 4.]]))

In [42]:
# 相乘
t_mul1 = a * b
t_mul2 = torch.mul(a, b)
print(t_mul1.shape, t_mul2.shape)
t_mul1, t_mul2

torch.Size([2, 2]) torch.Size([2, 2])


(tensor([[ 1.,  4.],
         [ 4., 16.]]),
 tensor([[ 1.,  4.],
         [ 4., 16.]]))

In [44]:
# 矩陣乘法
c = torch.randn((2,3))
d = torch.randn((3,4))

t_matmul1 = c.mm(d)
t_matmul2 = torch.mm(c,d)
t_matmul3 = torch.matmul(c,d)
t_matmul4 = c @ d

print(t_matmul1.shape, t_matmul2.shape, t_matmul3.shape, t_matmul4.shape)

torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([2, 4]) torch.Size([2, 4])


### 張量形狀操作

除了對張量進行運算外，針對張量的形狀(shape)進行操作也是一個很重要常用的功能。

像是在進行矩陣相乘前，我們可以把形狀不匹配的張量，先改變維度在進行矩陣相乘 (ex：2x3 的形狀改為 3x2 形狀)。

In [45]:
# 創健tensor
a = torch.tensor([[[1, 2, 3], [3, 4, 5]],
                    [[5, 6, 7], [7, 8, 9]]])
print(a.shape)
print(a)

torch.Size([2, 2, 3])
tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 9]]])


#### 1.  改變 tensor 的形狀：

reshape 與 view 皆可以用來改變 tensor 的形狀
在給定的形狀中，我們可以給 -1，代表這個維度的元素是剩下的所有元素個數

In [46]:
# 將tensor形狀由[2,2,3]改為[2,6]
b = a.reshape(2, 6)
c = a.view(2, 6)
d = a.reshape(2, -1)
print(b.shape, c.shape, d.shape)
b,c,d

torch.Size([2, 6]) torch.Size([2, 6]) torch.Size([2, 6])


(tensor([[1, 2, 3, 3, 4, 5],
         [5, 6, 7, 7, 8, 9]]),
 tensor([[1, 2, 3, 3, 4, 5],
         [5, 6, 7, 7, 8, 9]]),
 tensor([[1, 2, 3, 3, 4, 5],
         [5, 6, 7, 7, 8, 9]]))

#### 2.  變換 tensor 維度：

permute 給定輸出的維度順序，如 (0,2,1) 代表輸出的維度順序是原本張量維度的 0,2,1 順序
transpose 將給定維度進行對調，如 (1,2) 將原本的第 1 維與第 2 維進行對調

In [47]:
# 調換tensor維度
e = a.permute((0, 2, 1))
f = a.transpose(1,2)
print(e.shape, f.shape)
e, f

torch.Size([2, 3, 2]) torch.Size([2, 3, 2])


(tensor([[[1, 3],
          [2, 4],
          [3, 5]],
 
         [[5, 7],
          [6, 8],
          [7, 9]]]),
 tensor([[[1, 3],
          [2, 4],
          [3, 5]],
 
         [[5, 7],
          [6, 8],
          [7, 9]]]))

#### 3.增加維度

unsqueeze 在給定的位置增加維度
squeeze 握給定的維度元素數量為 1，則壓縮給定的位置 (若無給定則所有維度為 1 的位置都壓縮)

In [55]:
# 增加張量維度
g = torch.unsqueeze(a, dim=1) #增加維度在1的位置[0,1,2,3]
h = torch.squeeze(g) #壓縮為度為1的位置
print(g.shape, h.shape)

torch.Size([2, 1, 2, 3]) torch.Size([2, 2, 3])
